### ISSUE TITLE
Certificate has expired

### ISSUE THREAD

**Issue by Ligio** [trimmer-io/go-xmp#7]
When I run `go get trimmer.io/go-xmp` I have the following error:

`go: trimmer.io/go-xmp@v0.0.0-20200923092433-f9b6ca6c4a87: unrecognized import path "trimmer.io/go-xmp": https fetch: Get "https://trimmer.io/go-xmp?go-get=1": x509: certificate has expired or is not yet valid: current time 2021-01-11T13:05:37+01:00 is after 2021-01-08T09:52:26Z`

Your certificate has expired 4 days ago...

**Comment by echa** [comment]
The server ran into Letsencrypt's rate limit due to some error. Need to wait a bit. Sorry for the inconvenience.

**Comment by waschik** [comment]
There is still an issue with the certificate. Firefox writes "Websites prove their identity via certificates, which are valid for a set time period. The certificate for trimmer.io expired on 7/23/2021."

Would it not be easier to use directly github package instead of trimmer.io? But would require links inside project to be changed.

**Comment by echa** [comment]
Oh sorry. I changed the import and also added Go modules now.
